import { supabase } from './supabase'

/**
 * Persist a paid booking after Flitt confirms payment.
 *
 * Reads everything it needs from sessionStorage:
 *   - `pending_booking` — booking inputs stashed by Booking.jsx
 *   - `flitt_order_id`  — the Flitt order ID generated by Payment.jsx
 *
 * Side effects on success:
 *   - INSERTs a trip + bookings via the `book_trip` RPC (atomic; marks seats occupied)
 *   - UPDATEs the trip with payment_status='paid', payment_amount, flitt_order_id
 *   - PUSHes flight IDs onto localStorage["skybook_flight_ids"]
 *   - UPSERTs the first adult's name/dob/passport into the user's `profiles` row
 *   - CLEARs sessionStorage.pending_booking (but NOT flitt_order_id — caller decides)
 *   - FIRES the confirmation email (non-blocking; reported via `onEmailResult`)
 *
 * The whole body is wrapped in try/catch so synchronous throws (corrupt JSON,
 * Supabase client constructor errors, network exceptions thrown by the SDK,
 * localStorage quota errors) become structured failures rather than uncaught
 * exceptions that bubble into React's render and crash the page.
 *
 * @param {Object}   opts
 * @param {Object=}  opts.user            Logged-in user from useAuth(). Required for
 *                                        attribution; profile upsert is skipped when absent.
 * @param {Function=} opts.onEmailResult  Called with the email send error (or null on
 *                                        success) once Resend responds. Fire-and-forget.
 *
 * @returns {Promise<
 *   | { ok: true, tripId: string, ref: string, pending: object }
 *   | { ok: false, code: string, message: string, cause?: unknown }
 * >}
 *
 * Error codes:
 *   - `NO_PENDING`       — sessionStorage.pending_booking is missing
 *   - `BAD_PENDING`      — pending_booking exists but is not valid JSON
 *   - `SEAT_TAKEN`       — book_trip raised SEAT_TAKEN (race-condition seat conflict)
 *   - `BOOK_FAILED`      — book_trip raised any other Postgres error
 *   - `UNCAUGHT`         — any other thrown exception (network, sync error, …)
 */
export async function finalizeBooking({ user, onEmailResult } = {}) {
  // Outer guard for synchronous / SDK-thrown failures
  try {
    const raw = sessionStorage.getItem('pending_booking')
    if (!raw) {
      return { ok: false, code: 'NO_PENDING', message: 'No pending booking data found.' }
    }

    let pending
    try { pending = JSON.parse(raw) }
    catch {
      return { ok: false, code: 'BAD_PENDING', message: 'Pending booking data is corrupt.' }
    }

    const flittOrderId = sessionStorage.getItem('flitt_order_id')

    // 1. book_trip RPC — atomic seat check + trip insert + seat occupancy
    const { data: tripId, error: bookErr } = await supabase.rpc('book_trip', {
      p_trip_type:     pending.tripType,
      p_adults:        pending.adults,
      p_children:      pending.children,
      p_infants:       pending.infants,
      p_passengers:    pending.passengers,
      p_contact_email: pending.contactEmail,
      p_contact_phone: pending.contactPhone,
      p_user_id:       user?.id ?? null,
      p_bookings: [
        ...pending.outboundSeatIds.map(seatId => ({
          flight_id: pending.outboundFlightId,
          seat_id:   seatId,
          direction: 'outbound',
        })),
        ...(pending.returnFlightId
          ? pending.returnSeatIds.map(seatId => ({
              flight_id: pending.returnFlightId,
              seat_id:   seatId,
              direction: 'return',
            }))
          : []),
      ],
    })

    if (bookErr) {
      console.error('[finalize] book_trip error:', bookErr)
      return {
        ok: false,
        code: bookErr.message?.includes('SEAT_TAKEN') ? 'SEAT_TAKEN' : 'BOOK_FAILED',
        message: bookErr.message?.includes('SEAT_TAKEN')
          ? 'One of your seats was just booked by someone else. Your payment will be refunded — please contact support with your receipt.'
          : 'We received your payment but could not save your booking. Please contact support.',
        cause: bookErr,
      }
    }

    // 2. Stamp payment fields onto the trip (best-effort; non-fatal if it fails)
    const { error: updErr } = await supabase.from('trips').update({
      payment_status: 'paid',
      payment_amount: pending.total,
      flitt_order_id: flittOrderId,
    }).eq('id', tripId)
    if (updErr) console.warn('[finalize] trip update warning:', updErr)

    // 3. Track booked flight IDs locally (drives the "Booked" badge on FlightCard)
    try {
      const ids = JSON.parse(localStorage.getItem('skybook_flight_ids') || '[]')
      ids.push(pending.outboundFlightId)
      if (pending.returnFlightId) ids.push(pending.returnFlightId)
      localStorage.setItem('skybook_flight_ids', JSON.stringify(ids))
    } catch (storageErr) {
      // localStorage can throw on QuotaExceeded / private-mode Safari. Trip is
      // already saved — just log and continue.
      console.warn('[finalize] localStorage push failed:', storageErr)
    }

    // 3b. Save first adult's details to the user's profile so future bookings
    //     auto-fill Adult 1. Non-blocking — the booking itself already succeeded.
    if (user?.id && Array.isArray(pending.passengers)) {
      const leadAdult = pending.passengers.find(p => p.type === 'adult')
      if (leadAdult?.firstName && leadAdult?.lastName) {
        supabase
          .from('profiles')
          .upsert({
            user_id:    user.id,
            first_name: leadAdult.firstName,
            last_name:  leadAdult.lastName,
            dob:        leadAdult.dob       || null,
            passport:   leadAdult.passport  || null,
          }, { onConflict: 'user_id' })
          .then(({ error: profileErr }) => {
            if (profileErr) console.warn('[finalize] profile upsert failed:', profileErr)
          })
      }
    }

    // 4. Clear session — booking is final
    sessionStorage.removeItem('pending_booking')
    // NOTE: flitt_order_id is intentionally NOT cleared here. The caller decides
    // when to drop it — Payment.jsx keeps it around (alongside a `payment_finalized`
    // sentinel) so it can detect Flitt's late tail-redirect and bounce the user
    // straight to /my-bookings without re-mounting the widget.

    const ref = String(tripId).slice(0, 8).toUpperCase()

    // 5. Fire confirmation email (non-blocking)
    supabase.functions.invoke('send-booking-email', {
      body: {
        to:         pending.contactEmail,
        bookingRef: ref,
        tripType:   pending.tripType,
        passengers: pending.passengers,
        flights: {
          outbound: pending.outboundFlight,
          ...(pending.returnFlight ? { return: pending.returnFlight } : {}),
        },
        seats: {
          outbound: pending.outboundSeats,
          ...(pending.returnSeats?.length ? { return: pending.returnSeats } : {}),
        },
        totalPrice: pending.total,
      },
    }).then(({ error: emailErr }) => onEmailResult?.(emailErr))

    return { ok: true, tripId, ref, pending }
  } catch (err) {
    console.error('[finalize] uncaught error:', err)
    return {
      ok: false,
      code: 'UNCAUGHT',
      message: err?.message
        ? `Could not save your booking: ${err.message}`
        : 'Could not save your booking due to an unexpected error. Please retry.',
      cause: err,
    }
  }
}
