import { supabase } from './supabase'

/**
 * Persist a paid booking after Flitt confirms payment.
 *
 * Reads everything it needs from sessionStorage:
 *   - pending_booking : booking inputs stashed by Booking.jsx
 *   - flitt_order_id  : the Flitt order ID generated by Payment.jsx
 *
 * Side effects on success:
 *   - INSERTs a trip + bookings via the book_trip RPC (atomic; marks seats occupied)
 *   - UPDATEs the trip with payment_status='paid', payment_amount, flitt_order_id
 *   - PUSHes flight IDs onto localStorage["skybook_flight_ids"]
 *   - CLEARs sessionStorage (pending_booking, flitt_order_id)
 *   - FIRES the confirmation email (non-blocking, optional onEmailResult callback)
 *
 * Return shape:
 *   { ok: true,  tripId, ref, pending }
 *   { ok: false, code, message }
 *
 * The caller is responsible for UI (success card, error message, navigation).
 */
export async function finalizeBooking({ user, onEmailResult } = {}) {
  const raw = sessionStorage.getItem('pending_booking')
  if (!raw) {
    return { ok: false, code: 'NO_PENDING', message: 'No pending booking data found.' }
  }

  let pending
  try { pending = JSON.parse(raw) }
  catch {
    return { ok: false, code: 'BAD_PENDING', message: 'Pending booking data is corrupt.' }
  }

  const flittOrderId = sessionStorage.getItem('flitt_order_id')

  // 1. book_trip RPC — atomic seat check + trip insert + seat occupancy
  const { data: tripId, error: bookErr } = await supabase.rpc('book_trip', {
    p_trip_type:     pending.tripType,
    p_adults:        pending.adults,
    p_children:      pending.children,
    p_infants:       pending.infants,
    p_passengers:    pending.passengers,
    p_contact_email: pending.contactEmail,
    p_contact_phone: pending.contactPhone,
    p_user_id:       user?.id ?? null,
    p_bookings: [
      ...pending.outboundSeatIds.map(seatId => ({
        flight_id: pending.outboundFlightId,
        seat_id:   seatId,
        direction: 'outbound',
      })),
      ...(pending.returnFlightId
        ? pending.returnSeatIds.map(seatId => ({
            flight_id: pending.returnFlightId,
            seat_id:   seatId,
            direction: 'return',
          }))
        : []),
    ],
  })

  if (bookErr) {
    console.error('book_trip error:', bookErr)
    return {
      ok: false,
      code: bookErr.message?.includes('SEAT_TAKEN') ? 'SEAT_TAKEN' : 'BOOK_FAILED',
      message: bookErr.message?.includes('SEAT_TAKEN')
        ? 'One of your seats was just booked by someone else. Your payment will be refunded — please contact support with your receipt.'
        : 'We received your payment but could not save your booking. Please contact support.',
    }
  }

  // 2. Stamp payment fields onto the trip
  await supabase.from('trips').update({
    payment_status: 'paid',
    payment_amount: pending.total,
    flitt_order_id: flittOrderId,
  }).eq('id', tripId)

  // 3. Track booked flight IDs locally (drives the "Booked" badge on FlightCard)
  const ids = JSON.parse(localStorage.getItem('skybook_flight_ids') || '[]')
  ids.push(pending.outboundFlightId)
  if (pending.returnFlightId) ids.push(pending.returnFlightId)
  localStorage.setItem('skybook_flight_ids', JSON.stringify(ids))

  // 4. Clear session — booking is final
  sessionStorage.removeItem('pending_booking')
  // NOTE: flitt_order_id is intentionally NOT cleared here. The caller decides
  // when to drop it — Payment.jsx keeps it around (alongside a `payment_finalized`
  // sentinel) so it can detect Flitt's late tail-redirect and bounce the user
  // straight to /my-bookings without re-mounting the widget.

  const ref = String(tripId).slice(0, 8).toUpperCase()

  // 5. Fire confirmation email (non-blocking)
  supabase.functions.invoke('send-booking-email', {
    body: {
      to:         pending.contactEmail,
      bookingRef: ref,
      tripType:   pending.tripType,
      passengers: pending.passengers,
      flights: {
        outbound: pending.outboundFlight,
        ...(pending.returnFlight ? { return: pending.returnFlight } : {}),
      },
      seats: {
        outbound: pending.outboundSeats,
        ...(pending.returnSeats?.length ? { return: pending.returnSeats } : {}),
      },
      totalPrice: pending.total,
    },
  }).then(({ error: emailErr }) => onEmailResult?.(emailErr))

  return { ok: true, tripId, ref, pending }
}
