/**
 * Sends a branded SkyBook magic-link email via Resend, replacing Supabase's
 * default auth email. The token is still generated by Supabase (via the
 * admin API), but we control the SMTP path and HTML.
 *
 * POST body:
 *   { email: string, redirectTo?: string, isSignUp?: boolean }
 *
 * Required Supabase function secrets:
 *   SUPABASE_SERVICE_ROLE_KEY  — auto-populated by Supabase
 *   RESEND_API_KEY             — set via `supabase secrets set RESEND_API_KEY=...`
 *
 * Deploy with --no-verify-jwt because the frontend calls it pre-auth.
 */

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const CORS = {
  'Access-Control-Allow-Origin':  '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS, 'Content-Type': 'application/json' },
  })
}

// ── Email template ──────────────────────────────────────────────────────────
// Inline-CSS only, table-based layout — survives Outlook, Gmail, Apple Mail,
// Yahoo, etc. without bloating the HTML with conditional comments.

function buildEmailHtml(opts: { actionLink: string; isSignUp: boolean }) {
  const { actionLink, isSignUp } = opts

  const title = isSignUp ? 'Welcome to SkyBook' : 'Sign in to SkyBook'
  const lede  = isSignUp
    ? 'Click the button below to confirm your email and finish creating your account. The link expires in 1 hour.'
    : 'Click the button below to sign in to your SkyBook account. The link expires in 1 hour.'
  const cta   = isSignUp ? 'Create your account' : 'Sign in to SkyBook'

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title}</title>
</head>
<body style="margin:0; padding:0; background-color:#f1f5f9; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif; color:#0f172a;">
  <!-- Preheader (hidden but shown by mail clients in the inbox preview) -->
  <div style="display:none; max-height:0; overflow:hidden;">
    ${isSignUp ? 'Confirm your email to finish creating your SkyBook account.' : 'Your one-tap sign-in link for SkyBook.'}
  </div>

  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#f1f5f9; padding:40px 16px;">
    <tr>
      <td align="center">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:560px; width:100%; background-color:#ffffff; border-radius:16px; overflow:hidden; box-shadow:0 4px 24px rgba(15,23,42,0.08);">

          <!-- ─── Header ──────────────────────────────────────────────── -->
          <tr>
            <td align="center" style="background-color:#3B5BDB; padding:32px 24px;">
              <div style="color:#ffffff; font-size:28px; font-weight:800; letter-spacing:-0.5px; line-height:1;">
                <span style="font-size:32px; vertical-align:middle;">✈️</span>
                <span style="vertical-align:middle; margin-left:6px;">SkyBook</span>
              </div>
            </td>
          </tr>

          <!-- ─── Body ────────────────────────────────────────────────── -->
          <tr>
            <td style="padding:40px 32px 8px; text-align:center;">
              <h1 style="margin:0 0 12px; color:#0f172a; font-size:24px; font-weight:800; letter-spacing:-0.4px; line-height:1.3;">
                ${title}
              </h1>
              <p style="margin:0 0 32px; color:#64748b; font-size:15px; line-height:1.6;">
                ${lede}
              </p>

              <!-- ─── Primary CTA ─── -->
              <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:0 auto;">
                <tr>
                  <td align="center" style="background-color:#3B5BDB; border-radius:12px;">
                    <a href="${actionLink}" target="_blank" style="display:inline-block; padding:14px 36px; color:#ffffff; font-size:15px; font-weight:700; text-decoration:none; border-radius:12px; line-height:1.2;">
                      ${cta}
                    </a>
                  </td>
                </tr>
              </table>

              <!-- ─── Plain-text fallback link ─── -->
              <p style="margin:32px 0 8px; color:#94a3b8; font-size:13px;">
                Or copy and paste this link into your browser:
              </p>
              <p style="margin:0 0 32px; word-break:break-all;">
                <a href="${actionLink}" style="color:#3B5BDB; font-size:12px; font-family:'SF Mono',Monaco,Consolas,monospace; text-decoration:underline;">${actionLink}</a>
              </p>
            </td>
          </tr>

          <!-- ─── Footer ──────────────────────────────────────────────── -->
          <tr>
            <td style="padding:24px 32px 32px; border-top:1px solid #e2e8f0; text-align:center;">
              <p style="margin:0 0 4px; color:#94a3b8; font-size:12px; line-height:1.5;">
                If you didn't request this email, you can safely ignore it.<br>
                Someone may have typed your email address by mistake.
              </p>
              <p style="margin:12px 0 0; color:#cbd5e1; font-size:11px;">
                © ${new Date().getFullYear()} SkyBook · All rights reserved
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`
}

// ── Handler ─────────────────────────────────────────────────────────────────

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: CORS })
  if (req.method !== 'POST') {
    return json({ error: 'method_not_allowed', message: 'Use POST.' }, 405)
  }

  try {
    const { email, redirectTo, isSignUp } = await req.json()

    if (!email || typeof email !== 'string') {
      return json({ error: 'missing_fields', message: 'email is required.' }, 400)
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
    )

    // ── 1. Generate the action link server-side ────────────────────────────
    // Sign Up tab → type 'signup' (creates the user). If the email is already
    // registered, generateLink errors with "already registered" — fall back
    // to 'magiclink' so the user is signed into their existing account
    // (mirrors the silent-merge behaviour of signInWithOtp + shouldCreateUser).
    const linkOptions = redirectTo ? { redirectTo } : undefined
    let linkData: any = null
    let linkErr: any  = null

    if (isSignUp) {
      const r1 = await supabase.auth.admin.generateLink({
        type: 'signup',
        email,
        options: linkOptions,
      })
      linkData = r1.data
      linkErr  = r1.error

      if (linkErr && /already (registered|exists)/i.test(linkErr.message ?? '')) {
        console.log('[send-magic-link] User already exists — using magiclink type')
        const r2 = await supabase.auth.admin.generateLink({
          type: 'magiclink',
          email,
          options: linkOptions,
        })
        linkData = r2.data
        linkErr  = r2.error
      }
    } else {
      const r = await supabase.auth.admin.generateLink({
        type: 'magiclink',
        email,
        options: linkOptions,
      })
      linkData = r.data
      linkErr  = r.error
    }

    if (linkErr || !linkData?.properties?.action_link) {
      console.error('[send-magic-link] generateLink error:', linkErr)
      return json({
        error:   'link_generation_failed',
        message: linkErr?.message ?? 'Could not generate magic link for that email.',
      }, 400)
    }

    const actionLink = linkData.properties.action_link as string

    // ── 2. Send via Resend ─────────────────────────────────────────────────
    const html    = buildEmailHtml({ actionLink, isSignUp: Boolean(isSignUp) })
    const subject = isSignUp
      ? 'Welcome to SkyBook — confirm your email'
      : 'Your SkyBook sign-in link'

    const resendKey = Deno.env.get('RESEND_API_KEY')
    if (!resendKey) {
      console.error('[send-magic-link] RESEND_API_KEY is not set')
      return json({
        error:   'config_error',
        message: 'Email provider is not configured.',
      }, 500)
    }

    const resendRes = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${resendKey}`,
        'Content-Type':  'application/json',
      },
      body: JSON.stringify({
        from: 'SkyBook <onboarding@resend.dev>',
        to:   [email],
        subject,
        html,
      }),
    })

    if (!resendRes.ok) {
      const detail = await resendRes.text()
      console.error('[send-magic-link] Resend error:', detail)
      return json({
        error:   'email_provider_failed',
        message: 'Could not send the magic-link email.',
        details: detail,
      }, 502)
    }

    return json({ success: true })
  } catch (err) {
    console.error('[send-magic-link] error:', err)
    return json({
      error:   'internal_error',
      message: 'Internal server error while sending the magic link.',
    }, 500)
  }
})
